language: php
dist: bionic
sudo: false

php:
  - 7.0
  - 8.0
  - nightly

before_install: composer self-update
install: composer update --no-interaction --no-scripts

script:
  - composer run test

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache
    - vendor
